config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :work_details
  resources :patient_works
  resources :services
  resources :appointments
  resources :patients
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/work_detail.rb
class WorkDetail < ApplicationRecord
  belongs_to :patient_work
  belongs_to :service
end

app/controllers/work_details_controller.rb
class WorkDetailsController < ApplicationController
  before_action :set_work_detail, only: %i[ show edit update destroy ]

  # GET /work_details or /work_details.json
  def index
    @work_details = WorkDetail.all
  end

  # GET /work_details/1 or /work_details/1.json
  def show
  end

  # GET /work_details/new
  def new
    @work_detail = WorkDetail.new
  end

  # GET /work_details/1/edit
  def edit
  end

  # POST /work_details or /work_details.json
  def create
    @work_detail = WorkDetail.new(work_detail_params)

    respond_to do |format|
      if @work_detail.save
        format.html { redirect_to work_detail_url(@work_detail), notice: "Work detail was successfully created." }
        format.json { render :show, status: :created, location: @work_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_details/1 or /work_details/1.json
  def update
    respond_to do |format|
      if @work_detail.update(work_detail_params)
        format.html { redirect_to work_detail_url(@work_detail), notice: "Work detail was successfully updated." }
        format.json { render :show, status: :ok, location: @work_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_details/1 or /work_details/1.json
  def destroy
    @work_detail.destroy

    respond_to do |format|
      format.html { redirect_to work_details_url, notice: "Work detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_detail
      @work_detail = WorkDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_detail_params
      params.require(:work_detail).permit(:patient_work_id, :service_id)
    end
end

app/helpers/work_details_helper.rb
module WorkDetailsHelper
end

app/views/work_details/_form.html.erb
<%= form_with(model: work_detail) do |form| %>
  <% if work_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(work_detail.errors.count, "error") %> prohibited this work_detail from being saved:</h2>

      <ul>
        <% work_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patientWork_id, style: "display: block" %>
    <%= form.text_field :patient_work_id %>
  </div>

  <div>
    <%= form.label :service_id, style: "display: block" %>
    <%= form.text_field :service_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/work_details/_work_detail.html.erb
<div id="<%= dom_id work_detail %>">
  <p>
    <strong>Patientwork:</strong>
    <%= work_detail.patient_work_id %>
  </p>

  <p>
    <strong>Service:</strong>
    <%= work_detail.service_id %>
  </p>

</div>

app/views/work_details/edit.html.erb
<h1>Editing work detail</h1>

<%= render "form", work_detail: @work_detail %>

<br>

<div>
  <%= link_to "Show this work detail", @work_detail %> |
  <%= link_to "Back to work details", work_details_path %>
</div>

app/views/work_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Work details</h1>

<div id="work_details">
  <% @work_details.each do |work_detail| %>
    <%= render work_detail %>
    <p>
      <%= link_to "Show this work detail", work_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New work detail", new_work_detail_path %>

app/views/work_details/new.html.erb
<h1>New work detail</h1>

<%= render "form", work_detail: @work_detail %>

<br>

<div>
  <%= link_to "Back to work details", work_details_path %>
</div>

app/views/work_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @work_detail %>

<div>
  <%= link_to "Edit this work detail", edit_work_detail_path(@work_detail) %> |
  <%= link_to "Back to work details", work_details_path %>

  <%= button_to "Destroy this work detail", @work_detail, method: :delete %>
</div>