config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :work_details
  resources :patient_works
  resources :services
  resources :appointments
  resources :patients
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/patient_work.rb
class PatientWork < ApplicationRecord
  belongs_to :patient
end

app/controllers/patient_works_controller.rb
class PatientWorksController < ApplicationController
  before_action :set_patient_work, only: %i[ show edit update destroy ]

  # GET /patient_works or /patient_works.json
  def index
    @patient_works = PatientWork.all
  end

  # GET /patient_works/1 or /patient_works/1.json
  def show
  end

  # GET /patient_works/new
  def new
    @patient_work = PatientWork.new
  end

  # GET /patient_works/1/edit
  def edit
  end

  # POST /patient_works or /patient_works.json
  def create
    @patient_work = PatientWork.new(patient_work_params)

    respond_to do |format|
      if @patient_work.save
        format.html { redirect_to patient_work_url(@patient_work), notice: "Patient work was successfully created." }
        format.json { render :show, status: :created, location: @patient_work }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_works/1 or /patient_works/1.json
  def update
    respond_to do |format|
      if @patient_work.update(patient_work_params)
        format.html { redirect_to patient_work_url(@patient_work), notice: "Patient work was successfully updated." }
        format.json { render :show, status: :ok, location: @patient_work }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_works/1 or /patient_works/1.json
  def destroy
    @patient_work.destroy

    respond_to do |format|
      format.html { redirect_to patient_works_url, notice: "Patient work was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_work
      @patient_work = PatientWork.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_work_params
      params.require(:patient_work).permit(:description, :estimation, :discount, :patient_id)
    end
end

app/helpers/patient_works_helper.rb
module PatientWorksHelper
end

app/views/patient_works/_form.html.erb
<%= form_with(model: patient_work) do |form| %>
  <% if patient_work.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient_work.errors.count, "error") %> prohibited this patient_work from being saved:</h2>

      <ul>
        <% patient_work.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :estimation, style: "display: block" %>
    <%= form.text_field :estimation %>
  </div>

  <div>
    <%= form.label :discount, style: "display: block" %>
    <%= form.number_field :discount %>
  </div>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patient_works/_patient_work.html.erb
<div id="<%= dom_id patient_work %>">
  <p>
    <strong>Description:</strong>
    <%= patient_work.description %>
  </p>

  <p>
    <strong>Estimation:</strong>
    <%= patient_work.estimation %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= patient_work.discount %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= patient_work.patient_id %>
  </p>

</div>

app/views/patient_works/edit.html.erb
<h1>Editing patient work</h1>

<%= render "form", patient_work: @patient_work %>

<br>

<div>
  <%= link_to "Show this patient work", @patient_work %> |
  <%= link_to "Back to patient works", patient_works_path %>
</div>

app/views/patient_works/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patient works</h1>

<div id="patient_works">
  <% @patient_works.each do |patient_work| %>
    <%= render patient_work %>
    <p>
      <%= link_to "Show this patient work", patient_work %>
    </p>
  <% end %>
</div>

<%= link_to "New patient work", new_patient_work_path %>

app/views/patient_works/new.html.erb
<h1>New patient work</h1>

<%= render "form", patient_work: @patient_work %>

<br>

<div>
  <%= link_to "Back to patient works", patient_works_path %>
</div>

app/views/patient_works/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient_work %>

<div>
  <%= link_to "Edit this patient work", edit_patient_work_path(@patient_work) %> |
  <%= link_to "Back to patient works", patient_works_path %>

  <%= button_to "Destroy this patient work", @patient_work, method: :delete %>
</div>